apiVersion: v1
kind: Pod
metadata:
  name: secret-app
spec:
  containers:
  - name: secret-app
    image: alpine
    command: ['sh', '-c', "cat /etc/config/secret-app/password"]
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/config
        readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
        items:
              - key: password
                path: secret-app/password
